### ISSUE TITLE
Improving UI of User Profile

### ISSUE THREAD

**Issue by HarshitSharma4** [RishabhJain0721/Dorm-Deals-Frontend#16]
make this into more interactive way
![Screenshot from 2023-10-22 21-40-51](https://github.com/RishabhJain0721/Dorm-Deals-Frontend/assets/106171546/79af0a58-cf01-4f4f-8366-6783b075e2c5)

**Comment by HarshitSharma4** [comment]
assign this to me I want to work on this

**Comment by RishabhJain0721** [comment]
Okey go ahead
