### ISSUE TITLE
Login/ Signup loader

### ISSUE THREAD

**Issue by RishabhJain0721** [RishabhJain0721/Dorm-Deals-Frontend#2]
When a user clicks on **Login** and **Signup** buttons after entering the required details, I want to display a **_loader_** until the details are verified.
I have already used a loader called *InfinitySpin* from 'react-loader-spinner' package in Profile.js page. So, you can take reference from that. 

If you don't know what a loader is : 
A loader in web dev refers to the display that is visible to the user of a website while the rest of the page's content is still loading.

**Comment by AnsellMaximilian** [comment]
I can take this if that's okay

**Comment by RishabhJain0721** [comment]
Good to go 👍🏻
