### ISSUE TITLE
Navigation issues.

### ISSUE THREAD

**Issue by RishabhJain0721** [RishabhJain0721/Dorm-Deals-Frontend#21]
1. During an account creation, when a successful verification link is sent through email, user should get navigated to **signup** route.
       - *refer *Signup.js**
2. After listing an item, user should get navigated to dashboard.
       - *refer *Seller.js**

**Comment by Nailsonseat** [comment]
Can you assist this issue to me

**Comment by RishabhJain0721** [comment]
Alright go on @Nailsonseat
