### ISSUE TITLE
Add comments.

### ISSUE THREAD

**Issue by RishabhJain0721** [RishabhJain0721/Dorm-Deals-Frontend#6]
Add comments in the codebase to improve readability and remove garbage console.log() statements.

**Comment by yurii-vasyliev** [comment]
@RishabhJain0721 , I can take this one

**Comment by RishabhJain0721** [comment]
Alright, go on.

**Comment by satwikrprabhu** [comment]
Hey can i work on this? I can finish it asap.

**Comment by RishabhJain0721** [comment]
okay go on

**Comment by satwikrprabhu** [comment]
please check the pull request

**Comment by yurii-vasyliev** [comment]
@RishabhJain0721 , how about reviewing and merging my PR instead? A lot of work has been done there.
