### ISSUE TITLE
Search bar bug

### ISSUE THREAD

**Issue by RishabhJain0721** [RishabhJain0721/Dorm-Deals-Frontend#7]
Search bar is not working properly after first search. After the first search, when search button is clicked again, all items appear instead of just searched item.

**Comment by sgayathrii** [comment]
Hello, Can you assign this to me ?

**Comment by Pinaka-Pani-18** [comment]
Hi @RishabhJain0721, Can I work on this issue?

**Comment by RishabhJain0721** [comment]
@sgayathrii good to go
